apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coffee-app
  name: coffee-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee-app
  template:
    metadata:
      labels:
        app: coffee-app
    spec:
      containers:
      - image: quay.io/gauravkumar9130/coffee
        name: coffee
        ports:
        - containerPort: 80
