apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: coffee-app
  name: coffee-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: coffee-app
status:
  loadBalancer: {}
