apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotel-app
  name: hotel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-app
  template:
    metadata:
      labels:
        app: hotel-app
    spec:
      containers:
      - image: quay.io/gauravkumar9130/hotel
        name: hotel
        ports:
        - containerPort: 80
