apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tea-app
  name: tea-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tea-app
  template:
    metadata:
      labels:
        app: tea-app
    spec:
      containers:
      - image: quay.io/gauravkumar9130/tea
        name: tea
        ports:
        - containerPort: 80
