apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tea-app
  name: tea-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tea-app
status:
  loadBalancer: {}
